Modernize internal syntax and return Promises
janzal/twitter-media pull request #3
Opened 2017-07-13 02:39 UTC by cameronhunter

This PR results in a minor version change to the API, adding support for Promises while maintaining backwards compatibility.

Examples are converted to tests and assets are no longer included when npm installing the module.

2017-07-13 09:24 UTC, janzal requested changes
Looks much better now, thank you. There are just two small things to be checked and then we can merge.

2017-07-13 09:24 UTC, janzal commented on src/__tests__/index.js
> +jest.mock('../api-client');
Mocking api-client should be done before requiring TwitterMedia.

2017-07-13 09:24 UTC, janzal commented on src/api-client/index.js
> +                isOK ? resolve(body) : reject(new Error(`Error occurred fetching with params: ${JSON.stringify(params)}. Response: ${JSON.stringify(response)}`));
Stringifying params is probably not the best idea. It can contain buffer with image/video and it can mess up logs pretty easily.

2017-07-13 21:34 UTC, cameronhunter commented on src/__tests__/index.js
> +jest.mock('../api-client');
👍

2017-07-13 21:34 UTC, cameronhunter commented on src/api-client/index.js
> +                isOK ? resolve(body) : reject(new Error(`Error occurred fetching with params: ${JSON.stringify(params)}. Response: ${JSON.stringify(response)}`));
Makes a lot of sense – will figure something else out.

2017-07-13 22:51 UTC, janzal commented on src/__tests__/index.js
> +jest.mock('../api-client');
Awesome! This is much better now.

2017-07-13 22:51 UTC, janzal commented on src/api-client/index.js
> +    return JSON.stringify(
This is nice, but it does not work for the nested properties (`formData.media` is nested property).

2017-07-13 23:04 UTC, cameronhunter commented on src/api-client/index.js
> +    return JSON.stringify(
🤦‍♂️ of course

2017-07-17 19:22 UTC, cameronhunter commented
Is there anything left to do here before merging?

2017-07-19 09:00 UTC, janzal commented
Oh, sorry. I somehow missed your update. Thank you, looks good ;) Merging

2017-07-19 09:00 UTC, merged

2017-07-19 20:49 UTC, cameronhunter commented
Super! Can you update the thread with the version number when you publish? Thanks for accepting my PR.